package com.smartline.loan.entity.enums;

public enum ApplicationStatus {
    DRAFT,
    SUBMITTED,
    UNDER_VERIFICATION,
    VERIFIED,
    UNDER_CREDIT_ASSESSMENT,
    PENDING_FIELD_INSPECTION,
    FIELD_INSPECTION_COMPLETED,
    PENDING_SENIOR_APPROVAL,
    APPROVED,
    REJECTED,
    AGREEMENT_PENDING,
    AGREEMENT_VERIFIED,
    PENDING_DOWN_PAYMENT,
    PENDING_DISBURSAL,
    DISBURSED,
    CANCELLED
}
